apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snoprivileged
  annotations:
    rulehub.id: no.privileged.template
spec:
  crd:
    spec:
      names:
        kind: K8sNoPrivileged
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snoprivileged
        deny[msg] {
          some c
          c := input.review.object.spec.containers[_]
          c.securityContext.privileged == true
          msg := "privileged containers are not allowed"
        }
