apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingDepositLimitControls
metadata:
  name: betting-deposit_limit_controls
  annotations:
    rulehub.id: igaming.deposit_limit_controls
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
