apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingLicenseCheckUsPaPgcb
metadata:
  name: betting-license_check_us_pa_pgcb
  annotations:
    rulehub.id: igaming.license_check_us_pa_pgcb
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
