apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingLicenseCheckUkgc
metadata:
  name: betting-license_check_ukgc
  annotations:
    rulehub.id: igaming.license_check_ukgc
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
