apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingLicenseCheckDgojEs
metadata:
  name: betting-license_check_dgoj_es
  annotations:
    rulehub.id: igaming.license_check_dgoj_es
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
