apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingGeofencingRegulatedMarkets
metadata:
  name: betting-geofencing-regulated-markets
  annotations:
    rulehub.id: betting.geofencing_regulated_markets
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Namespace"]
    namespaces: ["*"]
  parameters:
    requiredLabel: jurisdiction
