apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingLicenseCheckDgojEs
metadata:
  name: betting-license-check-dgoj-es
  annotations:
    rulehub.id: betting.license_check_dgoj_es
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Namespace"]
    namespaces: ["*"]
  parameters:
    requiredLabel: jurisdiction
