apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingLicenseCheckAnjFr
metadata:
  name: betting-license_check_anj_fr
  annotations:
    rulehub.id: igaming.license_check_anj_fr
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
