apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingLicenseCheckAdmIt
metadata:
  name: betting-license_check_adm_it
  annotations:
    rulehub.id: igaming.license_check_adm_it
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
