apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingOfficialDataOnly
metadata:
  name: betting-official-data-only
  annotations:
    rulehub.id: betting.official_data_only
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Namespace"]
    namespaces: ["*"]
  parameters:
    requiredLabel: jurisdiction
