apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BettingSelfExclusionUkGamstop
metadata:
  name: betting-self_exclusion_uk_gamstop
  annotations:
    rulehub.id: igaming.self_exclusion_uk_gamstop
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    requiredLabel: jurisdiction
