apiVersion: constraints.gatekeeper.sh/v1beta1
kind: <Kind>
metadata:
  name: edtech-ferpa_consent_or_exception_for_disclosure
  annotations:
    rulehub.id: edtech.ferpa_consent_or_exception_for_disclosure
spec:
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["*"]
    namespaces: ["*"]
  parameters:
    <param1>: <value>
