apiVersion: constraints.gatekeeper.sh/v1beta1
kind: <Kind>
metadata:
  name: edtech-co_student_data_transparency
  annotations:
    rulehub.id: edtech.co_student_data_transparency
spec:
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["*"]
    namespaces: ["*"]
  parameters:
    <param1>: <value>
