apiVersion: constraints.gatekeeper.sh/v1beta1
kind: <Kind>
metadata:
  name: edtech-ct_student_data_privacy
  annotations:
    rulehub.id: edtech.ct_student_data_privacy
spec:
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["*"]
    namespaces: ["*"]
  parameters:
    <param1>: <value>
