apiVersion: constraints.gatekeeper.sh/v1beta1
kind: <Kind>
metadata:
  name: edtech-kr_pipa_guardian_consent_under_14
  annotations:
    rulehub.id: edtech.kr_pipa_guardian_consent_under_14
spec:
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["*"]
    namespaces: ["*"]
  parameters:
    <param1>: <value>
