name: Plugin Index Verify

on:
  pull_request:
    paths:
      - "manifest.json"
      - "files/**"
      - "hack/generate-plugin-index.sh"
      - "hack/verify-plugin-index.sh"
      - "Makefile"
  # Temporary: also run on push to main for visibility
  push:
    branches: [main]
    paths:
      - "manifest.json"
      - "files/**"
      - "hack/generate-plugin-index.sh"
      - "hack/verify-plugin-index.sh"
      - "Makefile"
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub charts image (e.g., 2025.10.03-<sha> or vX.Y.Z). Falls back to repo var CI_IMAGE_TAG or latest."
        required: false
        default: ""

jobs:
  guard:
    name: Require CI image tag (no drift)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Enforce pinned CI image tag
        shell: bash
        env:
          INPUT_CI_TAG: ${{ inputs.ci_image_tag }}
          VARS_CI_TAG: ${{ vars.CI_IMAGE_TAG }}
        run: bash hack/ci/enforce-pinned-ci-image-tag.sh
  verify:
    needs: guard
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository_owner }}/ci-charts:${{ inputs.ci_image_tag != '' && inputs.ci_image_tag || (vars.CI_IMAGE_TAG != '' && vars.CI_IMAGE_TAG || 'latest') }}"
      options: --user 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Assert jq present
        run: |
          command -v jq >/dev/null 2>&1 || { echo 'jq not found in ci-charts image'; exit 1; }
      - name: Generate plugin index
        run: make generate-plugin-index
      - name: Verify plugin index
        run: make verify-plugin-index
