name: Pre-commit

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.md"
      - ".pre-commit-config.yaml"
      - ".yamllint"
      - "hack/**"
  push:
    branches: [main]
    paths:
      - ".pre-commit-config.yaml"
      - ".yamllint"
      - "hack/**"
  workflow_dispatch:
    inputs:
      ci_image_tag:
        description: "CI image tag for RuleHub charts image (e.g., 2025.10.03-<sha> or vX.Y.Z). Falls back to repo var CI_IMAGE_TAG or latest."
        required: false
        default: ""

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      IS_ACT: "false"
    container:
      image: "ghcr.io/${{ github.repository_owner }}/ci-charts:${{ inputs.ci_image_tag != '' && inputs.ci_image_tag || (vars.CI_IMAGE_TAG != '' && vars.CI_IMAGE_TAG || 'latest') }}"
      options: --user 0:0
    steps:
      - name: Detect ACT environment
        shell: bash
        run: |
          if [ "${GITHUB_ACTOR:-}" = "nektos/act" ] || [ -n "${ACT:-}" ]; then
            echo "Detected ACT environment"
            echo "IS_ACT=true" >> "$GITHUB_ENV"
          else
            echo "Not running under ACT"
          fi
      - name: Cleanup cached actions (ACT)
        if: ${{ env.IS_ACT == 'true' }}
        shell: bash
        run: |
          # Remove stale cached actions injected under the repo path by act to avoid lstat failures during checkout
          rm -rf .github/_actions || true
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Verify pre-commit available
        run: |
          set -e
          command -v pre-commit >/dev/null 2>&1 || { echo 'pre-commit not found in ci-charts image'; exit 1; }
      - name: Run pre-commit (all files)
        id: precommit
        shell: bash
        continue-on-error: true
        env:
          PRE_COMMIT_COLOR: always
        run: |
          set -o pipefail
          pre-commit run --all-files --show-diff-on-failure | tee pre-commit.log
          code=${PIPESTATUS[0]:-0}
          echo "code=$code" >> "$GITHUB_OUTPUT"
      - name: Upload pre-commit log (GitHub only)
        if: ${{ always() && github.actor != 'nektos/act' }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: pre-commit-log
          path: pre-commit.log
          if-no-files-found: ignore

      - name: Show pre-commit log (ACT-friendly)
        if: ${{ always() && github.actor == 'nektos/act' }}
        shell: bash
        run: |
          echo "---- pre-commit exit code: ${{ steps.precommit.outputs.code }} ----"
          echo "---- pre-commit.log (last 300 lines) ----"
          if [ -f pre-commit.log ]; then
            tail -n 300 pre-commit.log || true
          else
            echo "pre-commit.log not found"
          fi
      - name: Fail if pre-commit failed (GitHub-hosted)
        if: ${{ steps.precommit.outputs.code != '0' && github.actor != 'nektos/act' }}
        run: |
          echo 'pre-commit found issues' >&2
          exit 1
      - name: Advisory summary (ACT)
        if: ${{ always() && github.actor == 'nektos/act' }}
        shell: bash
        run: |
          if [ "${{ steps.precommit.outputs.code }}" != "0" ]; then
            echo 'ACT: pre-commit found issues (advisory only, not failing under act).' >> "$GITHUB_STEP_SUMMARY"
          else
            echo 'ACT: pre-commit passed.' >> "$GITHUB_STEP_SUMMARY"
          fi
