name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # No-op on push to avoid skipped status while keeping manual control
  noop:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: No-op summary
        run: |
          echo "release-please: noop on push (temporary until tag-based migration)" >> "$GITHUB_STEP_SUMMARY"

  release:
    if: ${{ github.event_name == 'workflow_dispatch' && github.actor != 'nektos/act' }}
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
